### ISSUE TITLE
Error on delete single remaining character in document

### ISSUE THREAD

**Issue by millerdev** [editxt/editxt#13]
Open new document with command `xt new.py`
Type `:xt `
Backspace to beginning of document.
```
ERROR editxt - ObjC exception NSRangeException (reason: *** -[NSConcreteTextStorage attribute:atIndex:longestEffectiveRange:inRange:]: Range or index out of bounds) discarded
Stack trace (most recent call last):
  0x7fff5fbf96a0
  ffi_call_unix64 (in _objc.so) + 79
  -[NSConcreteTextStorage attribute:atIndex:longestEffectiveRange:inRange:] (in AppKit) + 118
  +[NSException raise:format:] (in CoreFoundation) + 204
  objc_exception_throw (in libobjc.A.dylib) + 43
  NSExceptionHandlerExceptionRaiser (in ExceptionHandling) + 172

ERROR editxt.textcommand - <function delete_backward at 0x10524a510> failed
Traceback (most recent call last):
  File "/Users/dmiller/Applications/EditXT.app/Contents/Resources/lib/python3.4/editxt/textcommand.py", line 657, in do_command_by_selector
  File "/Users/dmiller/Applications/EditXT.app/Contents/Resources/lib/python3.4/editxt/commands.py", line 527, in delete_backward
IndexError: NSRangeException - *** -[NSConcreteTextStorage attribute:atIndex:longestEffectiveRange:inRange:]: Range or index out of bounds
ERROR editxt - ObjC exception NSRangeException (reason: *** -[NSBigMutableString characterAtIndex:]: Index 0 out of bounds; string length 0) discarded
Stack trace (most recent call last):
  0x7fff5fbf7440
  ffi_call_unix64 (in _objc.so) + 79
  -[NSLayoutManager rectArrayForCharacterRange:withinSelectedCharacterRange:inTextContainer:rectCount:] (in AppKit) + 80
  -[NSLayoutManager(NSPrivate) _rectArrayForRange:withinSelectionRange:rangeIsCharRange:singleRectOnly:fullLineRectsOnly:inTextContainer:rectCount:rangeWithinContainer:glyphsDrawOutsideLines:] (in AppKit) + 7866
  -[NSBigMutableString characterAtIndex:] (in Foundation) + 98
  +[NSException raise:format:] (in CoreFoundation) + 204
  objc_exception_throw (in libobjc.A.dylib) + 43
  NSExceptionHandlerExceptionRaiser (in ExceptionHandling) + 172

ERROR editxt.util - unexpected error
Traceback (most recent call last):
  File "/Users/dmiller/Applications/EditXT.app/Contents/Resources/lib/python3.4/editxt/util.py", line 139, in wrapper
  File "/Users/dmiller/Applications/EditXT.app/Contents/Resources/lib/python3.4/editxt/controls/linenumberview.py", line 101, in drawRect_
  File "/Users/dmiller/Applications/EditXT.app/Contents/Resources/lib/python3.4/editxt/platform/mac/views/util.py", line 30, in wrapper
  File "/Users/dmiller/Applications/EditXT.app/Contents/Resources/lib/python3.4/editxt/controls/linenumberview.py", line 153, in draw_line_numbers
IndexError: NSRangeException - *** -[NSBigMutableString characterAtIndex:]: Index 0 out of bounds; string length 0
```

**Comment by millerdev** [comment]
Fixed by af47f771ba429a3da343924d3955cdddff501786
