### ISSUE TITLE
command bar path autocomplete is broken

### ISSUE THREAD

**Issue by joxl** [editxt/editxt#9]
Mac OSX Version: 10.10.1 (14B25)
EditXT Version: 1.7.5 (201501062056.e8def0a)

To reproduce (using `set project_path` command):
 - invoke command bar
 - type `set project_path ~/Code/Ard` + `[Tab]`

Observe:
 - nothing happens in command bar
 - Following error is appended to EditXT log:

    ```
ERROR editxt - *** Python exception discarded!
Traceback (most recent call last):
  File "/Users/Shared/Applications/EditXT.app/Contents/Resources/lib/python3.3/editxt/platform/mac/views/commandview.py", line 229, in textView_doCommandBySelector_
  File "/Users/Shared/Applications/EditXT.app/Contents/Resources/lib/python3.3/editxt/textcommand.py", line 102, in on_key_command
  File "/Users/Shared/Applications/EditXT.app/Contents/Resources/lib/python3.3/editxt/textcommand.py", line 150, in complete
  File "/Users/Shared/Applications/EditXT.app/Contents/Resources/lib/python3.3/editxt/textcommand.py", line 191, in _auto_complete
  File "/Users/Shared/Applications/EditXT.app/Contents/Resources/lib/python3.3/editxt/textcommand.py", line 348, in auto_complete
AssertionError: ('set project_path ~/Code/Ard', 27, 28)
```

Expected:
 - text `~/Code/Ard` to autocomplete to `~/Code/Arduino/`
 - no error

Continuing...
- invoke command bar
- type `set project_path ~/Code/Ardu` + `[Tab]`

Observe:
 - text `set project_path ~/Code/Ardu` autocompletes to `set project_path ~/Code/ArduArduino/`
 - no errors are appended to EditXT log

Expected:
 - text `~/Code/Ardu` to autocomplete to `~/Code/Arduino/`

**Comment by millerdev** [comment]
Fixed by 67b8f9626c72e7c7906f354f3594b6db189fa276, will be release in v1.7.6
